--- #YAML:1.0
name:               Dumbbench
version:            0.02
abstract:           Perl extension more reliable benchmarking
author:
    - Steffen Mueller <smueller@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Capture::Tiny:      0
    Carp:               0
    Class::XSAccessor:  1.05
    Number::WithError:  0
    Params::Util:       0
    Time::HiRes:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
